// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmmghddeqffzqorbiman.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbWdoZGRlcWZmenFvcmJpbWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0NTY3NjksImV4cCI6MjA0OTAzMjc2OX0.Ji5NYkioaKIaJX6poxClRboKb5h5fjoVNCtzesI7VBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);